- name: Setup Cluster
  hosts: servers
  remote_user: l1
  vars:
    master_ip: "192.168.16.140"
    node1_ip: "192.168.16.141"
    node2_ip: "192.168.16.142"

  roles: 
    - confighadoop
    - configelastic
